main_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'dashboard#index'

  get 'dashboard/index'

  devise_scope :user do
    get 'users/sign_in' => 'devise/sessions#new', :as => :login
  end

  resources :connectors, only: %i[index new create] do
    collection do
      post :import
      post :import_csv
    end
  end

  resources :financial_assets

  resources :accounts, only: %i[index update destroy] do
    member do
      post :merge
    end
  end

  resources :transactions do
    collection do
      get :export
      post :suggest_categories
    end
  end

  resources :transaction_rules do
    member do
      post :apply
      post :conditions
      get :preview
      get :next
      delete :delete_condition
    end
  end

  resources :categories

  resources :blocking_jobs, only: %(show)

  resources :example_banks, only: [:index, :show]
end

main_app/app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_user_references, only: %i[index update]
  before_action :set_transaction, only: %i[update destroy]
  before_action :set_columns, only: %i[index update]
  before_action :set_filter, only: %i[index suggest_categories]

  def index; end

  def export
    job = Transactions::ExportJob.perform_later(current_user, filters: params[:filter])

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          :background_processing_modal,
          partial: 'helpers/background_processing_modal',
          locals: { job_id: job.job_id }
        )
      end
    end
  end

  def update
    @transaction = Transactions::Update.call(current_user, @transaction,
      params.require(:transaction))
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          "transaction_row_#{@transaction.id}",
          partial: 'transactions/transaction_row',
          locals: { transaction: @transaction, references: @user_references, columns: @columns }
        )
      end
    end
  end

  def create
    @transaction = Transactions::Create.call(current_user, Transaction.new,
      params.require(:transaction))
    redirect_to transactions_path
  end

  def destroy
    @transaction.soft_delete
    redirect_params = params.to_unsafe_hash
    redirect_to transactions_path(filter: redirect_params[:filter],
      columns: redirect_params[:columns], page: redirect_params[:page])
  end

  def suggest_categories
    job = Transactions::SetSuggestedCategoriesJob.perform_later(current_user, params[:ids] || [])
    render json: { job_id: job.job_id }
  end

  private

  def set_columns
    default_columns = Transaction::DEFAULT_COLUMNS.map { |k| [k, '1'] }.to_h
    @columns = params[:columns] ? params[:columns].to_unsafe_hash : default_columns
  end

  def set_transaction
    @transaction = current_user.transactions.find(params[:id])
  end

  def set_filter
    @filter = Transactions::Model.new(current_user, params[:filter] || {})
  end
end

main_app/app/views/transactions/_columns.html.erb
<div 
  id="select_columns_modal" 
  tabindex="-1"
  aria-hidden="true"
  class="fixed left-0 right-0 top-0 z-50 hidden h-[calc(100%-1rem)] max-h-full w-full overflow-y-auto overflow-x-hidden p-4 md:inset-0"
  >
  <%= form_with url: transactions_path, method: :get, html: { id: 'select_columns_form' } do |form| %>
    <div class="relative bg-white rounded-lg shadow">
      <div aria-description="header" class="flex items-center justify-between p-4 md:p-5 border-b rounded-t">
        <h3 class="text-xl font-semibold text-gray-900">
          Select Columns
        </h3>
        <button data-action="click->transactions--index#close_columns_modal" type="button" class="text-gray-400 bg-transparent rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center">
          <%= render "icons/cross" %>
          <span class="sr-only">Close modal</span>
        </button>
      </div>
      <div aria-description="body" class="p-4 md:p-5 space-y-4">
        <%= form.fields_for :columns, @columns do |f| %>
          <% Transaction::COLUMNS.each do |key, options| %>
            <div class="flex items-center mb-4 w-64">
              <%= f.check_box key, id: "columns_#{key}", checked: @columns[key] == '1', class: 'w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded' %>
              <%= f.label key, options[:label], class: 'ml-2 text-sm text-gray-900' %>
            </div>
          <% end %>
        <%- end %>
      </div>
      <div aria-description="footer" class="flex items-center p-4 md:p-5 border-t border-gray-200 rounded-b justify-end justify-items-center">
        <button data-action="click->transactions--index#close_columns_modal" type="button" class="py-2.5 px-5 text-sm font-medium text-gray-900 bg-white rounded-lg border border-gray-200 ">Decline</button>
        <%= form.submit "Apply", class: 'cursor-pointer ms-3 text-white bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center' %>
      </div>
    </div>
    <% params[:filter]&.each do |key, value| %>
      <%= hidden_field_tag "filter[#{key}]", value %>
    <% end %>
    <input type="hidden" name="page" value="<%= params[:page] %>">
  <% end %>
</div>

main_app/app/views/transactions/_form.html.erb
<div class="mb-6">
  <%= f.label :date, 'Date', class: 'block mb-2 text-sm font-medium text-gray-900' %>
  <%= f.date_field :date, autofocus: true, autocomplete: "date", class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg block w-full p-2.5' %>
</div>
<div class="mb-6">
  <%= f.label :description, 'Description', class: 'block mb-2 text-sm font-medium text-gray-900' %>
  <%= f.text_field :description, autofocus: true, autocomplete: "description", class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg block w-full p-2.5' %>
</div>
<div class="mb-6">
  <%= f.label :amount, 'Amount', class: 'block mb-2 text-sm font-medium text-gray-900' %>
  <%= f.text_field :amount, autofocus: true, autocomplete: "description", class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg block w-full p-2.5' %>
</div>
<div class="mb-6">
  <%= f.label :category_id, 'Category', class: 'block mb-2 text-sm font-medium text-gray-900' %>
  <%= f.select :category_id, references[:categories], {}, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg block w-full p-2.5' %>
</div>
<%- unless f.object.persisted?%>
  <div class="mb-6">
    <%= f.label :account_id, 'Account', class: 'block mb-2 text-sm font-medium text-gray-900' %>
    <%= f.select :account_id, references[:accounts], {}, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg block w-full p-2.5' %>
  </div>
<% end %>
<div class="mb-6">
  <%= f.check_box :is_credit, autofocus: true, class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg p-2.5' %>
  <%= f.label :is_credit, 'Is Credit?', class: 'mb-2 text-sm font-medium text-gray-900' %>
</div>

main_app/app/views/transactions/_index_header.html.erb
<div class="mt-3 flex">
  <div class="flex space-x-2">
    <%= render 'transactions/search' %>
    <div class="flex">
      <button data-action="click->transactions--index#open_search" class="flex border border-gray-300 p-2 py-1.5 rounded-lg text-sm text-gray-500 items-center justify-center bg-white">
        <%= render 'icons/filter' %>
        <span class="pl-1">Filters</span>
      </button>
    </div>
  </div>
  <div class="ml-auto flex items-center space-x-2 sm:space-x-3">
    <button data-action="click->transactions--index#open_columns_modal" class="flex border border-gray-300 p-2 py-1.5 rounded-lg text-sm text-gray-500 items-center justify-center bg-white">
      <%= render 'icons/columns' %>
    </button>
    <button 
      class='flex p-2 py-1.5 rounded-lg text-sm text-white bg-primary-700 items-center justify-center' 
      data-action_url="<%= suggest_categories_transactions_url(request.params) %>"
      data-action="click->transactions--index#suggest_categories">
      <%= render 'icons/robot' %>
      <span class="pl-1">Suggest Categories</span>
    </button>
    <button data-action="click->transactions--index#open_add_drawer" class="flex p-2 py-1.5 rounded-lg text-sm text-white bg-primary-700 items-center justify-center">
      <%= render 'icons/plus' %>
      <span class="pl-1">Add Transaction</span>
    </button>
    <a href="<%= export_transactions_path(filter: (params[:filter] ? params[:filter].to_unsafe_h : {})) %>" data-turbo-stream class="flex border border-gray-300 p-2 py-1.5 rounded-lg text-sm text-gray-500 items-center justify-center bg-white" type="button">
      <%= render 'icons/export' %>
      <span class="pl-1">Export</span>
    </a>
  </div>
  <%= render "transactions/columns" %>
  <%= render "transactions/new" %>
</div>

main_app/app/views/transactions/_new.html.erb
<div id="new_transaction_drawer" class="fixed top-0 right-0 z-40 h-screen p-4 overflow-y-auto transition-transform translate-x-full bg-white w-80">
  <h5 id="drawer-label" class="inline-flex items-center mb-6 text-base font-semibold text-gray-500 uppercase">Create Transaction</h5>
  <button data-action="click->transactions--index#close_add_drawer" type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 absolute top-2.5 end-2.5 inline-flex items-center justify-center" >
    <%= render "icons/cross" %>
    <span class="sr-only">Close menu</span>
  </button>
  <%= form_with(model: Transaction.new, url: transactions_url(columns: @columns)) do |f| %>
    <%= render 'transactions/form', f: f, references: @user_references %>
    <div class="flex items-center justify-end">
      <button type="button" data-action="click->transactions--index#close_add_drawer" class="py-2.5 px-5 text-sm font-medium text-gray-900 bg-white rounded-lg border border-gray-200 ">Decline</button>
      <%= f.submit "Create", class: 'cursor-pointer ms-3 text-white bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center' %>
    </div>
  <% end %>
</div>

main_app/app/views/transactions/_search.html.erb
<%= form_for :filter, { url: transactions_path, method: :get, html: { id: 'transactions_search_form' } } do |f| %>
  <div class="p-2 py-1.5 flex border border-gray-300 rounded-lg bg-white">
    <%= render 'icons/search' %>
    <%= f.text_field :query, placeholder: 'Search for transactions', class: 'text-sm border-0 p-0 pl-2 w-52' %>
  </div>
  <input type="hidden" name="page" value="1">
  <div id="advance_search_drawer"  class="fixed top-0 right-0 z-40 h-screen p-4 overflow-y-auto transition-transform translate-x-full bg-white w-80">
    <h5 id="drawer-label" class="inline-flex items-center mb-6 text-base font-semibold text-gray-500 uppercase">Search Transactions</h5>
    <button type="button" data-action="click->transactions--index#close_search" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 absolute top-2.5 end-2.5 inline-flex items-center justify-center" >
      <%= render "icons/cross" %>
      <span class="sr-only">Close menu</span>
    </button>
    <div class="mb-6">
      <%= f.check_box :show_duplicates, class: 'w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded' %>
      <%= f.label :show_duplicates, 'Show Duplicates', class: 'ml-2 text-sm text-gray-900' %>
    </div>
    <div class="mb-6">
      <%= f.label :time_range, 'Time Range', class: 'block mb-2 text-sm font-medium text-gray-900' %>
      <%= f.select :time_range, @filter.selects[:time_ranges], {}, class: 'text-gray-900 text-sm rounded-lg inline-block bg-gray-50 text-gray-900 text-sm rounded-lg block w-full' %>
    </div>
    <div class="mb-6">
      <%= f.label :account_type, 'Account Type', class: 'block mb-2 text-sm font-medium text-gray-900' %>
      <%= f.select :account_type, @filter.selects[:account_types], {}, class: 'text-gray-900 text-sm rounded-lg inline-block bg-gray-50 text-gray-900 text-sm rounded-lg block w-full' %>
    </div>
    <div class="mb-6">
      <%= f.label :account_id, 'Account', class: 'block mb-2 text-sm font-medium text-gray-900' %>
      <%= f.select :account_id, @filter.selects[:accounts], {}, class: 'text-gray-900 text-sm rounded-lg inline-block bg-gray-50 text-gray-900 text-sm rounded-lg block w-full' %>
    </div>
    <div class="mb-6">
      <%= f.label :bank, 'Bank', class: 'block mb-2 text-sm font-medium text-gray-900' %>
      <%= f.select :bank, @filter.selects[:banks], {}, class: 'text-gray-900 text-sm rounded-lg inline-block bg-gray-50 text-gray-900 text-sm rounded-lg block w-full' %>
    </div>
    <div class="mb-6">
      <%= f.label :type, 'Type', class: 'block mb-2 text-sm font-medium text-gray-900' %>
      <%= f.select :type,@filter.selects[:types], {}, class: 'text-gray-900 text-sm rounded-lg inline-block bg-gray-50 text-gray-900 text-sm rounded-lg block w-full' %>
    </div>
    <div class="mb-6">
      <%= f.label :categories, 'Category', class: 'block mb-2 text-sm font-medium text-gray-900' %>
      <%= f.select :categories, @filter.selects[:categories], {}, multiple: true, class: 'text-gray-900 text-sm rounded-lg inline-block bg-gray-50 text-gray-900 text-sm rounded-lg block w-full' %>
    </div>
    <div class="flex items-center justify-end">
      <%= link_to "Reset", transactions_path, class: 'py-2.5 px-5 text-sm font-medium text-gray-900 bg-white rounded-lg border border-gray-200 ' %>
      <%= f.submit "Apply", class: 'cursor-pointer ms-3 text-white bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center' %>
    </div>
  </div>
  <% params[:columns]&.each do |key, value| %>
    <%= hidden_field_tag "columns[#{key}]", value %>
  <% end %>
<% end %>

main_app/app/views/transactions/_transaction_row.html.erb
<tr
    id="transaction_row_<%= transaction.id %>"
    data-controller="transactions--row"
    data-transaction_id="<%= transaction.id %>"
    class="bg-white border-b transaction_row">
    <%- Transaction::COLUMNS.each do |key| %>
      <%- if columns[key[0]].present? && columns[key[0]]== '1' %>
        <%- if key[0] == 'category_name' %>
          <td class="px-6 py-2">
            <button data-editable_attr="category" class="inline-flex items-center w-72" data-action="click->transactions--row#make_editable">
              <span class="hover:bg-yellow-50"><%=  Transaction::COLUMNS[key[0]][:value].call(transaction) %></span>
            </button>
            <%= form_with(model: transaction, url: transaction_url(id: transaction.id, columns: @columns),  class: 'inline-block hidden w-72 relative') do |f| %>
              <%= f.select :category_id, references[:categories], {}, class: 'text-gray-900 text-sm rounded-lg inline-block', data: { action: 'change->transactions--row#update_category' } %>
            <% end %>
          </td>
        <%- elsif key[0] == 'suggested_category' && transaction.suggested_category_id %>
          <td class="px-6 py-2">
            <div class="inline-flex items-center border border-gray-200 rounded-lg text-xs">
              <span class="inline-flex p-2 flex-1"><%=  Transaction::COLUMNS[key[0]][:value].call(transaction) %></span>
              <%= button_to transaction_path(transaction, {columns:}), method: :put, class: 'bg-green-50 p-2 rounded-r-lg', params: { transaction: {category_id: transaction.suggested_category.id} } do %>
                <svg class="h-4 w-4 text-green-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                </svg>
              <% end %>
            </div>
          </td>
        <%- else %>
          <td class="p-4 py-2">
            <%=  Transaction::COLUMNS[key[0]][:value].call(transaction) %>
          </td>
        <%- end %>
      <%- end %>
    <%- end %>
    <td class="p-4 py-2">
      <div class="flex">
        <button class="py-2" type="button" data-action="click->transactions--row#open_drawer">
          <%= render 'icons/edit' %>
        </button>
        <%= link_to transaction_path(transaction, request.query_parameters), class: 'py-2', data: { turbo_method: :delete, turbo_confirm: "Are you sure?", turbo_action: "replace" } do %>
          <%= render 'icons/delete' %>
        <% end %>
      </div>
      <!-- drawer component -->
      <div id="drawer-transaction-form-<%= transaction.id %>" class="fixed top-0 right-0 z-40 h-screen p-4 overflow-y-auto transition-transform translate-x-full bg-white w-80">
        <h5 id="drawer-label" class="inline-flex items-center mb-6 text-base font-semibold text-gray-500 uppercase">Update Transaction</h5>
        <button data-action="click->transactions--row#close_edit_drawer" type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 absolute top-2.5 end-2.5 inline-flex items-center justify-center" >
          <%= render "icons/cross" %>
          <span class="sr-only">Close menu</span>
        </button>
        <%= form_with(model: transaction, url: transaction_url(id: transaction.id, columns: @columns)) do |f| %>
          <%= render 'transactions/form', f: f, references: references %>
          <div class="flex items-center justify-end">
            <button type="button" data-action="click->transactions--row#close_edit_drawer" class="py-2.5 px-5 text-sm font-medium text-gray-900 bg-white rounded-lg border border-gray-200 ">Decline</button>
            <%= f.submit "Update", class: 'cursor-pointer ms-3 text-white bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center' %>
          </div>
        <% end %>
      </div>
    </td>
</tr>

main_app/app/views/transactions/_with_category_suggestions.html.erb
<div class="relative overflow-x-auto p-4 pt-0">
  <%= render(Transactions::ListComponent.new(
    user: user,
    columns: @columns,
    filter: filter,
    page: params[:page],
    options: { with_suggestions: true })
  ) %>
</div>

main_app/app/views/transactions/index.html.erb
<div id="transactions-page" class="p-2" data-controller="transactions--index">
  <div class="block items-center justify-between p-4">
    <div class="w-full">
      <div class="">
        <h1 class="text-xl font-semibold text-gray-900 sm:text-2xl">Your Transactions</h1>
      </div>
      <%= render 'transactions/index_header' %>
    </div>
  </div>
  <div id="transactions_list_frame" class="relative overflow-x-auto p-4 pt-0">
    <%= render(Transactions::ListComponent.new(
      user: current_user,
      columns: @columns,
      filter: @filter,
      page: params[:page],
      options: { with_suggestions: params[:with_suggestions], show_pagination: true }
    )) %>
  </div>
  <div id="background_processing_modal"></div>
</div>