main_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'dashboard#index'

  get 'dashboard/index'

  devise_scope :user do
    get 'users/sign_in' => 'devise/sessions#new', :as => :login
  end

  resources :connectors, only: %i[index new create] do
    collection do
      post :import
      post :import_csv
    end
  end

  resources :financial_assets

  resources :accounts, only: %i[index update destroy] do
    member do
      post :merge
    end
  end

  resources :transactions do
    collection do
      get :export
      post :suggest_categories
    end
  end

  resources :transaction_rules do
    member do
      post :apply
      post :conditions
      get :preview
      get :next
      delete :delete_condition
    end
  end

  resources :categories

  resources :blocking_jobs, only: %(show)

  resources :example_banks, only: [:index, :show]
end

main_app/app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :transactions, dependent: :nullify
  has_many :transaction_rules, dependent: :destroy
  belongs_to :parent_category, class_name: 'Category', optional: true

  before_create :set_code
  before_update :restore_code

  validates :name, presence: true

  def restore_code
    self.code = code_was
  end

  def set_code
    self.code = name.downcase.gsub(/\s+/, '_')
  end
end

main_app/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @parent_categories = current_user_repo.select_options[:parent_categories]
    @categories = current_user_repo.categories.order(updated_at: :desc)
  end

  def create
    raise 'Category name cannot be blank' if category_params[:name].blank?
    raise 'Parent category cannot be blank' if category_params[:parent_category_id].blank?

    current_user.categories.create!(category_params)
    redirect_to categories_path
  end

  def update
    @category = current_user.categories.find(params[:id])
    @category.update!(category_params)
    redirect_to categories_path
  end

  def new
    @parent_categories = current_user_repo.select_options[:parent_categories]
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          'new_category_form',
          template: 'categories/new',
          locals: { parent_categories: @parent_categories, model: Category.new }
        )
      end
      format.html { render html: '' }
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :parent_category_id)
  end
end

main_app/app/controllers/settings/categories_controller.rb
class Settings::CategoriesController < ApplicationController
  layout "settings"

  def index
    @parent_categories = current_user_repo.fetch_referencables[:parent_categories]
    @categories = current_user_repo.fetch_categories.order(updated_at: :desc)
  end

  def create
    raise "Category name cannot be blank" if category_params[:name].blank?
    raise "Parent category cannot be blank" if category_params[:parent_category_id].blank?

    current_user.categories.create!(category_params)
    redirect_to settings_categories_path
  end

  def update
    @category = current_user.categories.find(params[:id])
    @category.update!(category_params)
    redirect_to settings_categories_path
  end

  def new
    @parent_categories = current_user_repo.fetch_referencables[:parent_categories]
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          "new_category_form",
          template: "settings/categories/new",
          locals: { parent_categories: @parent_categories, model: Category.new },
        )
      end
      format.html { render html: "" }
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :parent_category_id)
  end
end

main_app/app/views/categories/_category_form.html.erb
<div class="mb-6">
  <%= f.label :name, 'Category Name', class: 'block mb-2 text-sm font-medium text-gray-900' %>
  <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: 'Category Name', class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg block w-full p-2.5' %>
</div>
<div class="mb-6">
  <%= f.label :parent_category_id, 'Parent Category', class: 'block mb-2 text-sm font-medium text-gray-900' %>
  <%= f.select :parent_category_id, parent_categories, {}, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg block w-full p-2.5' %>
</div>

main_app/app/views/categories/_category_row.html.erb
<tr
  data-controller="categories--row"
  data-category_id="<%= c.id %>"
  class="bg-white border-b">
  <td class="p-4 py-2">
    <%= c.name %>
  </td>
  <td class="p-4 py-2">
    <%= c.parent_category.name %>
  </td>
  <td class="p-4 py-2">
    <span class="inline-flex items-center rounded-md bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20"><%= c.code %></span>
  </td>
  <td class="p-4 py-2">
    <button class="text-white bg-blue-700 hover:bg-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 mb-2" type="button" data-action="click->categories--row#open_drawer">
      Update
    </button>
    <div
      id="category_form_<%= c.id %>"
      class="fixed top-0 right-0 z-40 h-screen p-4 overflow-y-auto transition-transform translate-x-full bg-white w-80">
      <h5 id="drawer-label" class="inline-flex items-center mb-6 text-base font-semibold text-gray-500 uppercase">Update Category</h5>
      <button data-action="click->categories--row#close_drawer" type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 absolute top-2.5 end-2.5 inline-flex items-center justify-center" >
        <%= render "icons/cross" %>
        <span class="sr-only">Close menu</span>
      </button>
      <%= form_with(model: c, url: category_url(id: c.id)) do |f| %>
        <%= render "categories/category_form", parent_categories: parent_categories, f: f %>
        <div class="flex items-center justify-end">
          <button type="button" data-action="click->categories--row#close_drawer" class="py-2.5 px-5 text-sm font-medium text-gray-900 bg-white rounded-lg border border-gray-200 ">Decline</button>
          <%= f.submit "Save", class: 'cursor-pointer ms-3 text-white bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center' %>
        </div>
      <% end %>
    </div>
  </td>
</tr>

main_app/app/views/categories/index.html.erb
<div id="categories-page" class="p-2">
  <div class="block items-center justify-between p-4">
    <div class="w-full">
      <div class="mb-4">
        <h1 class="text-xl font-semibold text-gray-900 sm:text-2xl">Your Categories</h1>
      </div>
      <div class="sm:flex">
        <div class="ml-auto flex items-center space-x-2 sm:space-x-3">
          <a class="flex p-2 py-1.5 rounded-lg text-sm text-white bg-primary-700 items-center justify-center" data-turbo-stream href="<%= new_category_path %>">
            <div class="flex items-center gap-x-3"><%= render 'icons/plus' %> Add Category</div>
          </a>
        </div>
      </div>
    </div>
  </div>
  <div class="relative overflow-x-auto p-4 pt-0">
    <div class="border border-gray-300 rounded-lg overflow-hidden">
      <table class="w-full text-sm text-left rtl:text-right text-gray-500">
        <thead class="text-xs text-white uppercase bg-gray-50">
          <tr>
            <th scope="col" class="p-4 border-blue-gray-100 bg-primary-700">
              <p class="block font-sans text-sm antialiased font-normal leading-none">Name</p>
            </th>
            <th scope="col" class="p-4 border-blue-gray-100 bg-primary-700">
              <p class="block font-sans text-sm antialiased font-normal leading-none">Parent Category</p>
            </th>
            <th scope="col" class="p-4 border-blue-gray-100 bg-primary-700">
              <p class="block font-sans text-sm antialiased font-normal leading-none">Code</p>
            </th>
            <th scope="col" class="p-4 border-blue-gray-100 bg-primary-700"></th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |c| %>
            <%= render('categories/category_row', c: c, parent_categories: @parent_categories) %>
          <% end %>
        </tbody>
      </table>
    </div>
    <div id="new_category_form"></div>
  </div>
</div>

main_app/app/views/categories/new.html.erb
<div
  data-controller="categories--new"
  id="new_category_form"
  class="fixed top-0 right-0 z-40 h-screen p-4 overflow-y-auto transition-transform translate-x-full bg-white w-80">
  <h5 id="drawer-label" class="inline-flex items-center mb-6 text-base font-semibold text-gray-500 uppercase">Add New Category</h5>
  <button data-action="click->categories--new#close_drawer" type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 absolute top-2.5 end-2.5 inline-flex items-center justify-center" >
    <%= render "icons/cross" %>
    <span class="sr-only">Close menu</span>
  </button>
  <%= form_with(model: Category.new, url: categories_url) do |f| %>
    <%= render "categories/category_form", parent_categories: parent_categories, f: f %>
    <div class="flex items-center justify-end">
      <button type="button" data-action="click->categories--new#close_drawer" class="py-2.5 px-5 text-sm font-medium text-gray-900 bg-white rounded-lg border border-gray-200 ">Decline</button>
      <%= f.submit "Save", class: 'cursor-pointer ms-3 text-white bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center' %>
    </div>
  <% end %>
</div>