main_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'dashboard#index'

  get 'dashboard/index'

  devise_scope :user do
    get 'users/sign_in' => 'devise/sessions#new', :as => :login
  end

  resources :connectors, only: %i[index new create] do
    collection do
      post :import
      post :import_csv
    end
  end

  resources :financial_assets

  resources :accounts, only: %i[index update destroy] do
    member do
      post :merge
    end
  end

  resources :transactions do
    collection do
      get :export
      post :suggest_categories
    end
  end

  resources :transaction_rules do
    member do
      post :apply
      post :conditions
      get :preview
      get :next
      delete :delete_condition
    end
  end

  resources :categories

  resources :blocking_jobs, only: %(show)

  resources :example_banks, only: [:index, :show]
end

main_app/app/models/connector.rb
class Connector < ApplicationRecord
  BANKS_CONFIG = {
    rbc: {
      name: 'Royal Bank of Canada',
      icon: 'rbc',
      color: '#006AC3',
      text_color: '#fff'
    },
    td: {
      name: 'TD Canada Trust',
      icon: 'td',
      color: '#008a00',
      text_color: '#fff'
    },
    walmart_mc: {
      name: 'Walmart Master Card',
      icon: 'walmart',
      color: '#ffc220',
      text_color: '#fff'
    },
    cibc: {
      name: 'Canadian Imperial Bank of Commerce (CIBC)',
      icon: 'cibc',
      color: '#dee9f7',
      text_color: '#8b1d41'
    },
    example_bank: {
      name: 'Example Bank',
      icon: 'example_bank',
      color: '#ff5733',
      text_color: '#ffffff'
    }
  }.with_indifferent_access

  enum :bank, { rbc: 1, td: 2, walmart_mc: 3, cibc: 4, example_bank: 5 }
  enum :auth_type, { persisted: 1, transient: 2 }, prefix: :auth_type
  enum :status, { connecting: 1, failed: 2, connected: 3 }, prefix: :status
  enum :auth_method, { extension: 1, direct: 2 }, prefix: :auth_method

  belongs_to :user
  has_many :accounts

  validates :bank, presence: true
  validates :auth_type, presence: true
  validates :username, presence: true, if: -> { auth_method == 'direct' }
  validates :password, presence: true, if: -> { auth_method == 'direct' }

  def bank_name
    BANKS_CONFIG[bank][:name]
  end

  def bank_icon
    BANKS_CONFIG[bank][:icon]
  end

  def bank_brand_color
    BANKS_CONFIG[bank][:color]
  end

  def bank_text_color
    BANKS_CONFIG[bank][:text_color]
  end

  def active_accounts
    accounts.where(is_active: true)
  end
end

main_app/app/controllers/connectors_controller.rb
class ConnectorsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: %i[import]
  before_action :set_user_references, only: %i[new index create]

  def import
    parameters = params.slice(:accounts, :bank).to_unsafe_hash
    job = Connectors::ImportBankJob.perform_later(parameters, current_user)
    render json: { job_id: job.job_id }
  end

  def import_csv
    file_import = current_user.file_imports.create!(file: params[:csv],
      input: { bank: params[:bank] })
    Connectors::ImportCsvFileJob.perform_later(file_import)
    render json: { file_import_id: file_import.id }
  end

  def index
    @connectors = current_user.connectors.preload(:accounts).select { |c| c.accounts.any? }
  end

  def new
    @bank = bank
    @mode = params[:mode]
    @connector = current_user.connectors.find_or_initialize_by(bank: @bank)
    locals = { bank: @bank, mode: @mode, connector: @connector, start_direct_process: false }
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(:new_connector, template: 'connectors/new',
          locals:)
      end

      format.html { render :new, locals: }
    end
  end

  def create
    @connector = current_user.connectors.find_or_initialize_by(bank:)
    @connector.assign_attributes(connector_params)
    @connector.save
    ConnectBankJob.perform_later(@connector) if @connector.valid?

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(:new_connector, template: 'connectors/new', locals: {
          connector: @connector,
          bank:,
          mode: params[:mode],
          start_direct_process: @connector.save
        })
      end
    end
  end

  def new_direct
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(:new_connector,
          template: 'connectors/new_direct')
      end

      format.html { render :new_direct }
    end
  end

  def create_direct
    render_lambda = lambda {
      render turbo_stream: turbo_stream.replace(:new_connector,
        partial: 'connectors/direct/connector_form')
    }

    if @connector.valid?
      ConnectBankJob.perform_later(connector_params)
      render_lambda = lambda {
        render turbo_stream: turbo_stream.replace(:connector_process,
          partial: 'connectors/direct/connector_process')
      }
    end

    respond_to { |format| format.turbo_stream(&render_lambda) }
  end

  private

  def bank
    params[:bank]
  end

  def connector_params
    params.require(:connector).permit(:auth_type, :username, :password, :two_factor_key,
      :auth_method)
  end
end

main_app/app/views/connectors/_connector_accounts.html.erb
<div class="mx-auto rounded-lg shadow-sm overflow-hidden bg-white mb-6">
  <!-- Bank Header -->
  <div class="bg-primary text-white p-4 flex justify-between items-center" style="background-color: <%= bank.bank_brand_color %> ">
    <div class="flex items-center space-x-3">
      <div style="background-color: <%= bank.bank_brand_color %>" class="w-10 h-10 bg-white rounded-md flex items-center justify-center">
        <%= render "icons/#{bank.bank_icon}" %>
      </div>
      <div style="color: <%= bank.bank_text_color %>">
        <h1 class="text-xl font-bold"><%= bank.bank_name %></h1>
        <p class="text-sm opacity-80">last updated <%= time_ago_in_words(bank.updated_at) %> ago</p>
      </div>
    </div>
    <div class="flex space-x-2">
      <%= link_to refresh_path, data: {'turbo-stream' => ''}, class: "bg-white text-primary hover:bg-gray-100 px-3 py-2 rounded-md flex items-center text-sm font-medium text-blue-600" do %>
        Refresh
      <% end %>
      <!--<button class="bg-white hover:bg-gray-100 px-3 py-2 rounded-md flex items-center text-sm font-medium text-blue-600">
        Hide Accounts
      </button>-->
    </div>
  </div>
  <!-- Accounts Table -->
  <table class="w-full">
    <thead>
      <tr class="bg-gray-100 text-left">
        <th scope="col" class="px-4 py-3 font-medium text-gray-700">
          Account Name
        </th>
        <th scope="col" class="px-4 py-3 font-medium text-gray-700">
          Nick Name
        </th>
        <th scope="col" class="px-4 py-3 font-medium text-gray-700">
          Type
        </th>
        <th scope="col" class="px-4 py-3 font-medium text-gray-700 text-right">
          Balance
        </th>
        <th scope="col" class="px-4 py-3 font-medium text-gray-700">
          Actions
        </th>
      </tr>
    </thead>
    <tbody class="divide-y divide-gray-200">
      <% accounts.each do |account| %>
        <%= render "accounts/account_row", account: account, bank_options: bank_options, account_types: account_types %>
      <% end %>
    </tbody>
  </table>
</div>

main_app/app/views/connectors/_connector_form.html.erb
<div 
  id="new_connector"
  data-action="connector_process:close_modal@window->new_connector#close_modal"
  data-controller="new_connector"
  tabindex="-1" 
  aria-hidden="true"
  class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
  <div class="relative p-4 w-full max-w-2xl max-h-full">
    <!-- Modal content -->
    <div id="new_connector_form" class="relative bg-white rounded-lg shadow dark:bg-gray-700">
      <%= form_with(method: 'post', model: @connector, url: create_connector_path(id: params['id'])) do |f| %>
        <!-- Modal header -->
        <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
          <h3 class="text-xl font-semibold text-gray-900 dark:text-white">
            Connect with <%= @bank_name %>
          </h3>
          <button type="button" data-action="click->new_connector#close_modal" class="text-gray-400 bg-transparent rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center">
            <%= render "icons/cross" %>
            <span class="sr-only">Close modal</span>
          </button>
        </div>
        <!-- Modal body -->
        <div class="p-4 md:p-5 space-y-4">
          <% if @connector.errors.any? %>
            <div class="form-errors p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50">
              <h2><%= pluralize(@connector.errors.count, "error") %> prohibited this article from being saved:</h2>
              <ul class="m-4">
                <% @connector.errors.each do |error| %>
                  <li class="ml-4"><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div>
            <%= f.label :username, 'Your Bank Username', class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
            <%= f.text_field :username, autofocus: true, autocomplete: "username", placeholder: 'name@company.com', class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg block w-full p-2.5' %>
          </div>
          <div>
            <%= f.label :password, 'Your Bank Password', class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
            <%= f.password_field :password, autocomplete: "password", placeholder: '••••••••', class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg block w-full p-2.5' %>
          </div>
          <div>
            <%= f.radio_button :auth_type, "persisted", class: 'w-4 h-4 text-blue-600 bg-gray-100 border-gray-300' %>
            <%= f.label :auth_type_persisted, "I want to save my credentials for future use", class: 'ms-2 text-sm font-medium text-gray-900 ' %>
          </div>
          <div>
            <%= f.radio_button :auth_type, "transient", class: 'w-4 h-4 text-blue-600 bg-gray-100 border-gray-300' %>
            <%= f.label :auth_type_transient, "I don't wany my credentials saved", class: 'ms-2 text-sm font-medium text-gray-900 ' %>
          </div>
        </div>
        <!-- Modal footer -->
        <div class="flex items-center p-4 md:p-5 border-t border-gray-200 rounded-b justify-end justify-items-center">
          <button data-action="click->new_connector#close_modal" type="button" class="py-2.5 px-5 text-sm font-medium text-gray-900 bg-white rounded-lg border border-gray-200 ">Decline</button>
          <%= f.submit "Connect", class: 'cursor-pointer ms-3 text-white bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center' %>
        </div>
      <% end %>
    </div>
    <div id="connector_process"></div>
  </div>
</div>

main_app/app/views/connectors/_connector_process.html.erb
<div data-bank_id="<%= params['id'] %>" data-user_id="<%= @current_user.id %>" data-controller="connector_process" id="connector_process" class="relative bg-white rounded-lg shadow dark:bg-gray-700">
  <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
    <h3 class="text-xl font-semibold text-gray-900 dark:text-white">
      Connect with <%= @bank_name %>
    </h3>
    <button type="button" class="text-gray-400 bg-transparent rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center">
      <%= render "icons/cross" %>
      <span class="sr-only">Close modal</span>
    </button>
  </div>
  <!-- Modal body -->
  <div class="p-4 md:p-5 space-y-4">
    <div class="flex items-center justify-center w-100 h-32">
      <div role="status">
        <%= render 'icons/loading-spinner' %>
        <span class="sr-only">Loading...</span>
      </div>
    </div>
    <div class="flex justify-center align-items-center progress-message text-sm" id="initiating">We are connecting with your bank</div>
    <div class="flex justify-center align-items-center progress-message text-sm hidden" id="logging_in">We are logging in your bank account</div>
    <div class="progress-message hidden" id="confirm_two_factor_notification">
      <div class="flex justify-center align-items-center text-sm m-4">You should have received notification, please confirm when you have allowed access</div>
      <div class="flex justify-center align-items-center">
        <button data-action="click->connector_process#send_two_factor" class="text-white bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2">Confirm Access</button>
      </div>
    </div>
    <div class="flex justify-center align-items-center progress-message text-sm hidden" id="received_connector_prompt">Recieved Two Factor</div>
    <div class="flex justify-center align-items-center progress-message text-sm hidden" id="login_complete">Login is successful</div>
  </div>
  <!-- Modal footer -->
  <div class="flex items-center p-4 md:p-5 border-t border-gray-200 rounded-b justify-end justify-items-center">
    <button data-action="click->connector_process#close_modal" type="button" class="py-2.5 px-5 text-sm font-medium text-gray-900 bg-white rounded-lg border border-gray-200 ">Decline</button>
  </div>
</div>

main_app/app/views/connectors/index.html.erb
<div id="connectors-page">
  <div class="p-6 relative overflow-x-auto">
    <div class="flex mb-4">
      <div class="text-2xl my-4">Connected Banks</div>
      <div class="flex flex-1 justify-end items-center">
        <%= link_to "Add New", new_connector_path, class: 'p-2 py-1.5 rounded-lg text-sm text-white bg-primary-700', data: {'turbo-stream' => ''} %>
      </div>
    </div>
    <div>
      <% @connectors.each do |connector| %>
        <%= render "connectors/connector_accounts", 
            bank: connector, 
            accounts: connector.accounts, 
            bank_options: @user_references[:banks], 
            account_types: @user_references[:account_types],
            refresh_path: new_connector_path(bank: connector.bank) %>
      <% end %>
    </div>
  </div>
</div>
<div id="new_connector"></div>

main_app/app/views/connectors/new.html.erb
<div 
  id="new_connector"
  tabindex="-1" 
  class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full"
  data-controller="connectors--new">
  <%- if mode.blank?  %>
    <%= render 'connectors/options/select' %>
  <%- elsif mode == 'import' %>
    <%= render 'connectors/options/import' %>
  <%- elsif mode == 'extension' %>
    <%= render 'connectors/options/extension' %>
  <%- elsif mode == 'login' %>
    <%= render 'connectors/options/login', start_direct_process: start_direct_process %>
  <%- end %>
</div>