main_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'dashboard#index'

  get 'dashboard/index'

  devise_scope :user do
    get 'users/sign_in' => 'devise/sessions#new', :as => :login
  end

  resources :connectors, only: %i[index new create] do
    collection do
      post :import
      post :import_csv
    end
  end

  resources :financial_assets

  resources :accounts, only: %i[index update destroy] do
    member do
      post :merge
    end
  end

  resources :transactions do
    collection do
      get :export
      post :suggest_categories
    end
  end

  resources :transaction_rules do
    member do
      post :apply
      post :conditions
      get :preview
      get :next
      delete :delete_condition
    end
  end

  resources :categories

  resources :blocking_jobs, only: %(show)

  resources :example_banks, only: [:index, :show]
end

main_app/app/models/account.rb
class Account < ApplicationRecord
  include SoftDeletable

  ACCOUNT_TYPE_LABELS = {
    credit_card: 'Credit Card',
    deposit_account: 'Deposit/Chequing Account',
    investment: 'Investment',
    credit_line: 'Line of Credit',
    mortgage: 'Mortgage'
  }.freeze

  POSITIVE_ACCOUNTS = %i[deposit_account investment].freeze

  NEGATIVE_ACCOUNTS = %i[credit_card mortgage credit_line].freeze

  FILTERABLE_ACCOUNT_TYPES = %i[credit_card deposit_account].freeze

  enum :account_type, { credit_card: 1, deposit_account: 2, investment: 3, credit_line: 4,
                       mortgage: 5 }
  validates :external_id, uniqueness: { scope: :connector }

  belongs_to :connector
  has_many :transactions

  def account_type_label
    ACCOUNT_TYPE_LABELS[account_type.to_sym]
  end

  def active?
    is_active
  end

  def other_accounts
    connector.active_accounts.where.not(id:).where(account_type:)
  end
end

main_app/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[update merge destroy]
  before_action :set_selects, only: %i[index update]

  def index
    @accounts = current_user.accounts.preload(:connector)
  end

  def update
    @account.update!(account_params)
    @account.reload
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          "account-row-#{@account.id}",
          partial: 'accounts/account_row',
          locals: { account: @account, bank_options: @bank_options,
                    account_types: @account_types }
        )
      end
      format.html { render html: '' }
    end
  end

  def merge
    target_id = params.permit(:target_id)[:target_id]
    Accounts::Merge.call(@account, target_id)
    redirect_to connectors_path, notice: 'Account merged successfully'
  end

  def destroy
    @account.soft_delete
    redirect_to connectors_path, notice: 'Account deleted successfully'
  end

  private

  def set_account
    @account = current_user.accounts.find(params['id'])
  end

  def account_params
    params.require(:account).permit(:name, :nick_name)
  end

  def set_selects
    selects = current_user_repo.select_options
    @bank_options = selects[:banks]
    @account_types = selects[:account_types]
  end

  def render_account_row; end
end

main_app/app/views/accounts/_account_form.html.erb
<%= form_with(method: 'PUT', model: account, url: account_url(id: account.id)) do |f| %>
  <div class="mb-6">
    <%= f.label :name, 'Account Name', class: 'block mb-2 text-sm font-medium text-gray-900' %>
    <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: 'Bank Account Name', class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg block w-full p-2.5' %>
  </div>
  <div class="mb-6">
    <%= f.label :nick_name, 'Nick Name', class: 'block mb-2 text-sm font-medium text-gray-900' %>
    <%= f.text_field :nick_name, autofocus: true, autocomplete: "nick_name", placeholder: 'Bank Account Nick Name', class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg block w-full p-2.5' %>
  </div>
  <div class="mb-6">
    <%= f.label :balance, 'Account Balance', class: 'block mb-2 text-sm font-medium text-gray-900' %>
    <%= f.text_field :balance, disabled: true, autofocus: true, autocomplete: "balance", placeholder: 'Bank Account Nick Name', class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg block w-full p-2.5' %>
  </div>
  <div class="mb-6">
    <%= f.label :connector_id, 'Bank', class: 'block mb-2 text-sm font-medium text-gray-900' %>
    <%= f.select :connector_id, bank_options, {}, disabled: true, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg block w-full p-2.5' %>
  </div>
  <div class="mb-6">
    <%= f.label :account_type, 'Account Type', class: 'block mb-2 text-sm font-medium text-gray-900' %>
    <%= f.select :account_type, account_types, {}, disabled: true, class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg block w-full p-2.5' %>
  </div>
  <div class="flex items-center justify-end">
    <button type="button" data-action="click->accounts--row#close_drawer" class="py-2.5 px-5 text-sm font-medium text-gray-900 bg-white rounded-lg border border-gray-200 ">Decline</button>
    <%= f.submit "Update", class: 'cursor-pointer ms-3 text-white bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center' %>
  </div>
<% end %>

main_app/app/views/accounts/_account_merge_form.html.erb
<%= form_tag(merge_account_url(id: account.id), method: :post) do %>
  <div class="mb-6">
    <label for="target_id" class="block mb-2 text-sm font-medium text-gray-900">Select Account to Merge</label>
    <%= select_tag :target_id, options_for_select(
    account.other_accounts.map { |acc| [acc.nick_name.empty? ? acc.name : acc.nick_name, acc.id] },
    params[:selected_option]
  ), class: 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg block w-full p-2.5' %>
  </div>
  <div class="flex items-center justify-end">
    <button type="button" data-action="click->accounts--row#close_merge_drawer" class="py-2.5 px-5 text-sm font-medium text-gray-900 bg-white rounded-lg border border-gray-200 ">Decline</button>
    <%= submit_tag "Merge", class: 'cursor-pointer ms-3 text-white bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center' %>
  </div>
<% end %>

main_app/app/views/accounts/_account_row.html.erb
<tr 
  data-controller="accounts--row"
  data-account_id="<%= account.id %>"
  class="<%= account.active? ? '' : 'bg-gray-50' %>" 
  id="account-row-<%= account.id %>">
  <td class="px-4 py-4">
    <div class="flex items-center">
      <span class="<%= account.active? ? 'font-medium' : 'text-gray-500 font-medium' %>">
        <%= account.name %>
      </span>
      <% unless account.active? %>
        <span class="ml-2 px-2 py-1 text-xs bg-amber-100 text-amber-800 rounded-full">
          Inactive
        </span>
      <% end %>
    </div>
  </td>
  <td class="p-4"><%= account.nick_name %></td>
  <td class="px-4 py-4 <%= account.active? ? '' : 'text-gray-500' %>">
    <%= account.account_type_label %>
  </td>
  <td class="px-4 py-4 text-right font-medium">
    <%= account.balance %>
  </td>
  <td class="px-4 py-4 w-40">
    <div class="flex items-center">
      <button class="p-2 px-1 text-gray-500 hover:bg-gray-100 rounded-md" type="button" data-action="click->accounts--row#open_drawer">
        <%= render 'icons/edit' %>
      </button>
      <%- unless account.active? %>
        <button class="p-2 px-1 text-gray-500 hover:bg-gray-100 rounded-md" type="button" data-action="click->accounts--row#open_merge_drawer">
          <%= render 'icons/merge' %>
        </button>
      <%-end %>
      <%= link_to account_path(account), class: 'p-2 px-1 text-gray-500 hover:bg-gray-100 rounded-md', data: { turbo_method: :delete, turbo_confirm: "Are you sure?", turbo_action: "replace" } do %>
        <%= render 'icons/delete' %>
      <% end %>
    </div>
    <!-- drawer component -->
    <%= render 'helpers/right_drawer',
      drawer_id: "drawer-account-form-#{account.id}",
      title: "Update Account",
      close_action: "click->accounts--row#close_drawer" do %>
      <%= render "accounts/account_form", account: account, bank_options: bank_options, account_types: account_types %>
    <%- end %>
    <%= render 'helpers/right_drawer',
      drawer_id: "drawer-account-merge-form-#{account.id}",
      title: "Merge Account",
      close_action: "click->accounts--row#close_merge_drawer" do %>
      <%= render "accounts/account_merge_form", account: account, bank_options: bank_options, account_types: account_types %>
    <%- end %>
  </td>
</tr>

main_app/app/views/accounts/index.html.erb
<div id="accounts-page">
  <div class="block items-center justify-between border-b border-gray-200 bg-white p-4 sm:flex">
    <div class="mb-1 w-full">
      <div class="mb-4">
        <%= render 'helpers/breadcrumbs', crumbs: [['Accounts']] %>
        <h1 class="text-xl font-semibold text-gray-900 sm:text-2xl">Your Accounts</h1>
      </div>
    </div>
  </div>
  <div class="relative overflow-x-auto">
    <table class="w-full">
      <thead>
        <tr class="bg-gray-100 text-left">
          <th scope="col" class="px-4 py-3 font-medium text-gray-700">
            Account Name
          </th>
          <th scope="col" class="px-4 py-3 font-medium text-gray-700">
            Type
          </th>
          <th scope="col" class="px-4 py-3 font-medium text-gray-700 text-right">
            Balance
          </th>
          <th scope="col" class="px-4 py-3 font-medium text-gray-700">
            Bank
          </th>
          <th></th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-200">
        <% @accounts.each do |a| %>
          <%= render "accounts/account_row", account: a, bank_options: @bank_options, account_types: @account_types %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>